### ISSUE TITLE
Disabling Trigger doesn't work

### ISSUE THREAD

**Issue by fboucherBHVR** [MothCocoon/FlowSolo#1]
https://github.com/MothCocoon/FlowSamples/blob/452f54603a715143177236659bbc7ae380799a00/Source/FlowQuest/Private/Triggers/FlowTriggerComponent.cpp#L41

Think you need to actually Emplace the CollisionComponent

**Comment by MothDoctor** [comment]
Thanks for pointing this out, @fboucherBHVR! 
Fixed :)
